### ISSUE TITLE
Assumes Etherpad accessible over HTTP (versus HTTPS)

### ISSUE THREAD

**Issue by dowen-atomicjolt** [atomicjolt/etherpad_canvas#10]
See https://github.com/atomicjolt/etherpad_canvas/blob/0800f6acdb835d5f9c13e0556e3b250936758071/lib/etherpad_canvas/etherpad_collaboration.rb#L23.

Preferred fix: The plugin should either accept an entire base URL (e.g. "https://my-etherpad.example.org/sub-path").  When it constructs the final URL of the document for the redirect, it must be sure to handle trailing slashes correctly.

**Comment by emdurr** [comment]
Recent pull request #12 resolved this issue
